// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owtesbwrkcdbjrwndefn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dGVzYndya2NkYmpyd25kZWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjg4ODMsImV4cCI6MjA2OTIwNDg4M30.dkSxPeXmd8DLMBV_wHMFDlS1T_3og37btJRA2rI_p-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});